### ISSUE TITLE
Parse additional cellranger outputs

### ISSUE THREAD

**Issue by chris-rands** [becavin-lab/checkatlas#20]
Thank you for the nice looking tool. Would you consider adding to the multiQC reports parsing outputs from additional cellranger files? I'm thinking the metrics_summary.csv and (less easily) the web_summary.html for each sample. The .csv files could be aggregated into a table with basic quality scores, mapping metrics etc. The web_summary.html file is harder to parse I guess, but ideally could capture the knee plots of UMI counts for a quick comparison across samples.

Best wishes, Chris

**Comment by drbecavin** [comment]
Hello, thanks for the message !
That is part of my plan. Do you have some experience in MultiQC ? IIt would be niice to have some help in adding Cellanger parsing to MultiQC.
We can also contact MultiQC projet developer to get some help. II am sure the single-cell bioinfo community would be happy to have that capability !

**Comment by drbecavin** [comment]
I can see that it is in progress but was not finished : https://github.com/ewels/MultiQC/issues/751

**Comment by drbecavin** [comment]
Ok, never mind ! The module is finished. It waits for the PR to be accepted
https://github.com/ewels/MultiQC/pull/1689
